M48
; DRILL file {KiCad 8.0.4} date 2024-11-06T13:18:38+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-06T13:18:38+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X2.3811Y-4.4488
X7.3827Y-4.1103
X7.3827Y-4.7677
T2
X5.2894Y-3.0984
X6.3878Y-5.002
M30
